/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InfoForm.java
 *
 * Created on Apr 2, 2012, 9:01:15 PM
 */

//package stv;
import javax.swing.JFileChooser;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 *
 * @author bergurth
 */
public class InfoForm extends javax.swing.JFrame {

    /** Creates new form InfoForm */
    
    BufferedImage mImage;
    public BufferedImage RImage;
    int[][] pixels;
    String name1;
    int w;
    int h;
    int w2;
    int h2;
    int Mx;
    int My;
    int Mh2;
    int Mw2;
    int k = 0;
    Complex a;
    Complex b;
    Complex c;
    Complex d;




    public InfoForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ReATextField = new javax.swing.JTextField();
        ReBTextField = new javax.swing.JTextField();
        ReCTextField = new javax.swing.JTextField();
        ReDTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ImATextField = new javax.swing.JTextField();
        ImBTextField = new javax.swing.JTextField();
        ImCTextField = new javax.swing.JTextField();
        ImDTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jHeightTextField = new javax.swing.JTextField();
        jWidthTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Choose values for cooefficients of transformation, then open file.");

        jLabel2.setText("f(z) = (az + b)/(cz + d).");

        jLabel3.setText("Image File:");

        jButton1.setText("Open");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Re(a):");

        jLabel5.setText("Re(b):");

        jLabel6.setText("Re(c):");

        jLabel7.setText("Re(d):");

        ReATextField.setText("1.0");
        ReATextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReATextFieldActionPerformed(evt);
            }
        });

        ReBTextField.setText("0.0");
        ReBTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReBTextFieldActionPerformed(evt);
            }
        });

        ReCTextField.setText("0.0");

        ReDTextField.setText("1.0");

        jLabel8.setText("Im(a):");

        jLabel9.setText("Im(b):");

        jLabel10.setText("Im(c):");

        jLabel11.setText("Im(d):");

        ImATextField.setText("0.0");

        ImBTextField.setText("0.0");

        ImCTextField.setText("0.0");

        ImDTextField.setText("0.0");

        jButton2.setText("Save  Image");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Help");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jHeightTextField.setText("0");
        jHeightTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHeightTextFieldActionPerformed(evt);
            }
        });

        jWidthTextField.setText("0");

        jLabel12.setText("height:");

        jLabel13.setText("width:");

        jRadioButton1.setText("Inverse f fill");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jHeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jWidthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                        .addComponent(jRadioButton1))
                                    .addComponent(jLabel13)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(ReDTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(ReCTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(ReATextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(ReBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ImATextField, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ImBTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ImCTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ImDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(52, 52, 52))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ReATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(ImATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ReBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(ImBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ReCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(ImCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ReDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(ImDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton2))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jHeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jWidthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton1))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Select Image");
        chooser.setFileFilter(new FileFilterM());

        int Checker = chooser.showOpenDialog(null);
        name1 = chooser.getSelectedFile().getAbsolutePath();
        jTextField1.setText(name1);

           JFrame frm=new JFrame(name1);
        frm.setLocation(200,200);


                File inputFile = new File(name1);
	try {
            mImage = ImageIO.read(inputFile);
        }
        catch (IOException ex) {
            //Logger.getLogger(index.class.getName()).log(Level.SEVERE, null, ex);                                                           \

        }



        int w = mImage.getWidth();
        int h = mImage.getHeight();
        int Mx = w/2;
        int My = h/2;




         int[][] pixels = new int[w][h];

         for( int i = 0; i < w; i++ )
            for( int j = 0; j < h; j++ )
                {
                pixels[i][j] = mImage.getRGB( i, j );
                System.out.println("Loading..");
                }


int h2 = (Integer.valueOf((jHeightTextField.getText())));
int w2 = (Integer.valueOf((jWidthTextField.getText())));
int Mh2 = h2/2;
int Mw2 = w2/2;
		if((h2==0)||(w2==0)){
         RImage = new BufferedImage(w,h,BufferedImage.TYPE_INT_RGB);
                h2=h;
                w2=w;
                } else
          RImage = new BufferedImage(w2,h2,BufferedImage.TYPE_INT_RGB);
	  

      Complex a = new Complex((Double.valueOf((ReATextField.getText()).trim()).doubleValue()),(Double.valueOf((ImATextField.getText()).trim()).doubleValue()));
	Complex b = new Complex((Double.valueOf((ReBTextField.getText()).trim()).doubleValue()),(Double.valueOf((ImBTextField.getText()).trim()).doubleValue()));
        Complex c = new Complex((Double.valueOf((ReCTextField.getText()).trim()).doubleValue()),(Double.valueOf((ImCTextField.getText()).trim()).doubleValue()));
	Complex d = new Complex((Double.valueOf((ReDTextField.getText()).trim()).doubleValue()),(Double.valueOf((ImDTextField.getText()).trim()).doubleValue()));
Complex Zero = new Complex(0.0,0.0);
if(k == 0){
          for( int i = w-1; i > 0; i-- )
            for( int j = h-1; j > 0; j-- )
                {
                    System.out.println("Transforming..");
                    Complex C = new Complex((double)(i-Mx),(double)(j-My));
                    Complex Z = new Complex(((a.mul(C)).add(b)).div((c.mul(C)).add(d)));

                    int ReT = ((int)(Z.getRe())+Mx);
                    int ImT = ((int)(Z.getIm())+My);
                    if((ReT<w2)&&(ReT>=0)&&(ImT<h2)&&(ImT>=0))
                    RImage.setRGB(ReT,ImT,pixels[i][j]);

                }
        }
 else{
        for( int i = w2-1; i > 0; i-- )
            for( int j = h2-1; j > 0; j-- )
                {
                    System.out.println("Transforming..");
                    Complex C = new Complex((double)(i-Mw2),(double)(j-Mh2));
// Creates number C for each pixel on the end target Buffered Image
                 //   c = Zero.sub(c);
// makes complex c negative
                    Complex Z = new Complex(((d.mul(C)).sub(b)).div((c.mul(C)).add(a)));
// creates number f-1(z) in this case f-1(c) 
                    int ReT = ((int)(Z.getRe())+Mx);
                    int ImT = ((int)(Z.getIm())+My);
// gets integers for real and imaginary parts of f-1(z). And readjusts for java coordinate system, (formerly +Mx and +My).
                    if((ReT<w)&&(ReT>=0)&&(ImT<h)&&(ImT>=0))
                    RImage.setRGB(i,j,pixels[ReT][ImT]);
            }

 }
System.out.println("The width is "+w+" The height is "+h);
System.out.println("The width2 is "+w2+" The height2 is "+h2);

                JLabel lb=new JLabel(new ImageIcon(RImage));
	frm.getContentPane().add(lb);
	frm.show();
	frm.pack();





    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void ReATextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReATextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReATextFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

          JFileChooser chooser2 = new JFileChooser(".");
        chooser2.setDialogTitle("Select Image");
       // chooser.setFileFilter(new FileFilterM());

         int Checker = chooser2.showSaveDialog(null);
        try {

        File outputfile = new File(chooser2.getSelectedFile().getName());
        ImageIO.write(RImage, "jpg", outputfile);
        }
        catch(IOException ex){
        }


    //Save

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed


        new Help().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jHeightTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHeightTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHeightTextFieldActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
       if (k == 0)
           k = 1;
       else
           k = 0;
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void ReBTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReBTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReBTextFieldActionPerformed

    /**
    * @param args the command line arguments
    */

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ImATextField;
    private javax.swing.JTextField ImBTextField;
    private javax.swing.JTextField ImCTextField;
    private javax.swing.JTextField ImDTextField;
    private javax.swing.JTextField ReATextField;
    private javax.swing.JTextField ReBTextField;
    private javax.swing.JTextField ReCTextField;
    private javax.swing.JTextField ReDTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jHeightTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jWidthTextField;
    // End of variables declaration//GEN-END:variables

}
